# -*- coding: utf-8 -*-
"""Codingan Project Individu KCV Fix mi no revisi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mWL-Yre5QNHqk7s9X-Sr03HRPXd_IV8-

**Perbandingan Kinerja Model CNN, ResNet50, dan YOLOv8 dalam Klasifikasi Penyakit Daun Kakao Berbasis Citra Digital**

**Install & Import Libabry yang di butuhkan**
"""

# Install library tambahan
!pip install ultralytics

# Import library
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import random
import seaborn as sns
import pandas as pd

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras import layers, models

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

from ultralytics import YOLO

"""**Load Data**"""

import os

from google.colab import drive
drive.mount('/content/drive')

"""**Data Preparation**"""

import cv2

base_path = "/content/drive/MyDrive/Project Individu Deep Learning/Dataset Daun Kokoa/Dataset Daun Kokoa (CNN and Resnet)/train"

classes = os.listdir(base_path)

plt.figure(figsize=(12, 8))

for i, cls in enumerate(classes):
    class_path = os.path.join(base_path, cls)
    imgs = random.sample(os.listdir(class_path), 3)

    for j, img_name in enumerate(imgs):
        img_path = os.path.join(class_path, img_name)
        img = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)

        plt.subplot(len(classes), 3, i*3 + j + 1)
        plt.imshow(img)
        plt.title(cls)
        plt.axis('off')

# Menghitung Jumlah Dataset Perkeles Secara Keseluruhan

def count_dataset(base_path):

    print(f"\n📂 Dataset: {base_path}")
    total_all = 0

    for split in ['train', 'valid', 'test']:
        split_path = os.path.join(base_path, split)

        if not os.path.exists(split_path):
            print(f"\n⚠️ {split} tidak ditemukan")
            continue

        print(f"\n🔹 {split.upper()}")
        total_split = 0

        for cls in os.listdir(split_path):
            class_path = os.path.join(split_path, cls)

            if os.path.isdir(class_path):
                count = len([
                    f for f in os.listdir(class_path)
                    if f.lower().endswith(('.jpg', '.png', '.jpeg'))
                ])

                print(f"{cls}: {count}")
                total_split += count

        print(f"➡️ Total {split}: {total_split}")
        total_all += total_split

    print(f"\n🔥 TOTAL DATASET: {total_all}")

dataset_path = "/content/drive/MyDrive/Project Individu Deep Learning/Dataset Daun Kokoa/Dataset Daun Kokoa (CNN and Resnet)"

count_dataset(dataset_path)

"""**Data Preprocessing**"""

#Set Parameter
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import random

base_path = "/content/drive/MyDrive/Project Individu Deep Learning/Dataset Daun Kokoa/Dataset Daun Kokoa (CNN and Resnet)/train"

classes = os.listdir(base_path)
img_size = (224, 224)

#Preprocessing Resize dan Normalization
def preprocess_image(img_path):
    # read image
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # resize
    resized = cv2.resize(img, img_size)

    # normalization
    normalized = resized / 255.0

    return img, resized, normalized

#Data Augmentation

def augment_image(image):
    image = image.copy()

    h, w = image.shape[:2]

    # ======================
    # 1. Horizontal Flip (masih OK)
    # ======================
    if random.random() > 0.5:
        image = np.fliplr(image)

    # ======================
    # 2. Rotasi (lebih realistis)
    # ======================
    angle = random.randint(-20, 20)
    M = cv2.getRotationMatrix2D((w//2, h//2), angle, 1)
    image = cv2.warpAffine(image, M, (w, h))

    # ======================
    # 3. Zoom ringan
    # ======================
    scale = random.uniform(0.9, 1.1)
    M = cv2.getRotationMatrix2D((w//2, h//2), 0, scale)
    image = cv2.warpAffine(image, M, (w, h))

    # ======================
    # 4. Translasi (geser posisi)
    # ======================
    tx = random.randint(-10, 10)
    ty = random.randint(-10, 10)
    M = np.float32([[1, 0, tx], [0, 1, ty]])
    image = cv2.warpAffine(image, M, (w, h))

    # ======================
    # 5. Brightness (lebih aman)
    # ======================
    image = np.clip(image * random.uniform(0.8, 1.2), 0, 255)

    return image.astype(np.uint8)

# VISUALISASI BEFORE vs AFTER (INI YANG PENTING)

plt.figure(figsize=(16, 10))

rows = len(classes)

for i, cls in enumerate(classes):
    class_path = os.path.join(base_path, cls)
    img_name = random.choice(os.listdir(class_path))
    img_path = os.path.join(class_path, img_name)

    # preprocessing
    original, resized, normalized = preprocess_image(img_path)
    augmented = augment_image(resized)

    print("=== CONTOH NILAI PIXEL ===")
    print("Original min-max:", original.min(), original.max())
    print("Normalized min-max:", normalized.min(), normalized.max())

    # =========================
    # DISPLAY
    # =========================

    # ORIGINAL
    plt.subplot(rows, 4, i*4 + 1)
    plt.imshow(original)
    plt.title(f"{cls}\nOriginal")
    plt.axis('off')

    # RESIZED
    plt.subplot(rows, 4, i*4 + 2)
    plt.imshow(resized)
    plt.title("Resized (224x224)")
    plt.axis('off')

    # NORMALIZED (DI SCALE BIAR KELIHATAN)
    plt.subplot(rows, 4, i*4 + 3)
    plt.imshow((normalized * 255).astype(np.uint8))
    plt.title("Normalized (scaled)")
    plt.axis('off')

    # AUGMENTED
    plt.subplot(rows, 4, i*4 + 4)
    plt.imshow(augmented)
    plt.title("Augmented")
    plt.axis('off')

plt.tight_layout()
plt.show()

plt.figure(figsize=(16, 10))

rows = len(classes)

for i, cls in enumerate(classes):
    class_path = os.path.join(base_path, cls)
    img_name = random.choice(os.listdir(class_path))
    img_path = os.path.join(class_path, img_name)

    # preprocessing
    original, resized, normalized = preprocess_image(img_path)
    augmented = augment_image(resized)

    # =========================
    # HISTOGRAM ORIGINAL
    # =========================
    plt.subplot(rows, 4, i*4 + 1)
    plt.hist(original.ravel(), bins=50)
    plt.title(f"{cls}\nOriginal")

    # =========================
    # HISTOGRAM RESIZED
    # =========================
    plt.subplot(rows, 4, i*4 + 2)
    plt.hist(resized.ravel(), bins=50)
    plt.title("Resized")

    # =========================
    # HISTOGRAM NORMALIZED
    # =========================
    plt.subplot(rows, 4, i*4 + 3)
    plt.hist(normalized.ravel(), bins=50)
    plt.title("Normalized")

    # =========================
    # HISTOGRAM AUGMENTED
    # =========================
    plt.subplot(rows, 4, i*4 + 4)
    plt.hist(augmented.ravel(), bins=50)
    plt.title("Augmented")

plt.tight_layout()
plt.show()

"""**Load Dataset (Tidak Split Data)**"""

train_path = "/content/drive/MyDrive/Project Individu Deep Learning/Dataset Daun Kokoa/Dataset Daun Kokoa (CNN and Resnet)/train"
valid_path = "/content/drive/MyDrive/Project Individu Deep Learning/Dataset Daun Kokoa/Dataset Daun Kokoa (CNN and Resnet)/valid"
test_path  = "/content/drive/MyDrive/Project Individu Deep Learning/Dataset Daun Kokoa/Dataset Daun Kokoa (CNN and Resnet)/test"

# Data Generator
from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.1,
    width_shift_range=0.05,
    height_shift_range=0.05,
    brightness_range=[0.8, 1.2],
    horizontal_flip=True
)

val_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    train_path,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True
)

val_gen = val_datagen.flow_from_directory(
    valid_path,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False   # penting
)

test_gen = test_datagen.flow_from_directory(
    test_path,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False   # penting
)

class_names = list(test_gen.class_indices.keys())

"""**Train Model**"""

from tensorflow.keras import layers, models
from tensorflow.keras.layers import Dropout
from tensorflow.keras.regularizers import l2

cnn_model = models.Sequential([
    layers.Conv2D(32, 3, activation='relu', input_shape=(224,224,3)),
    layers.BatchNormalization(),
    layers.MaxPooling2D(),

    layers.Conv2D(64, 3, activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling2D(),

    layers.Conv2D(128, 3, activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling2D(),

    layers.GlobalAveragePooling2D(),

    layers.Dense(128, activation='relu', kernel_regularizer=l2(0.001)),
    layers.Dropout(0.5),

    layers.Dense(len(train_gen.class_indices), activation='softmax')
])

cnn_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

base_model = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

# freeze sebagian besar layer
base_model.trainable = True
for layer in base_model.layers[-30:]:
    layer.trainable = False

x = layers.GlobalAveragePooling2D()(base_model.output)
x = layers.BatchNormalization()(x)
x = layers.Dense(128, activation='relu')(x)
x = layers.Dropout(0.2)(x)

output = layers.Dense(len(train_gen.class_indices), activation='softmax')(x)

resnet_model = models.Model(inputs=base_model.input, outputs=output)

resnet_model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

cnn_history = cnn_model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=10,
)

resnet_history = resnet_model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=10,

)

yolo_model = YOLO('yolov8n.pt')

yolo_model.train(
    data="/content/drive/MyDrive/Project Individu Deep Learning/Dataset Daun Kokoa/Dataset Daun Kokoa (Yolov8)/data.yaml",  # train + val + test
    epochs=20,
    imgsz=640,

    # INI YANG PENTING
    project="/content/drive/MyDrive/Project Individu Deep Learning/Dataset Daun Kokoa/Dataset Daun Kokoa (Yolov8)/results",
    name="exp_yolo"
)

import collections

train_count = collections.Counter(train_gen.classes)
val_count = collections.Counter(val_gen.classes)
test_count = collections.Counter(test_gen.classes)

print("TRAIN distribution:", train_count)
print("VAL distribution:", val_count)
print("TEST distribution:", test_count)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

def evaluate(model, test_gen, title):

    y_pred = model.predict(test_gen)
    y_pred = np.argmax(y_pred, axis=1)
    y_true = test_gen.classes

    labels = list(test_gen.class_indices.keys())

    print(f"\n===== {title} Classification Report =====")
    print(classification_report(y_true, y_pred, target_names=labels))

    cm = confusion_matrix(y_true, y_pred)

    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=labels,
                yticklabels=labels)
    plt.title(f"{title} Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

    return accuracy_score(y_true, y_pred)

y_pred = np.argmax(cnn_model.predict(val_gen), axis=1)

print("Predicted distribution:")
print(collections.Counter(y_pred))

cnn_acc = evaluate(cnn_model, test_gen, "CNN")

resnet_acc = evaluate(resnet_model, test_gen, "ResNet50")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

yolo_test_img = "/content/drive/MyDrive/Project Individu Deep Learning/Dataset Daun Kokoa/Dataset Daun Kokoa (Yolov8)/test/images"
yolo_test_lbl = "/content/drive/MyDrive/Project Individu Deep Learning/Dataset Daun Kokoa/Dataset Daun Kokoa (Yolov8)/test/labels"

def get_label(path):
    if not os.path.exists(path):
        return -1
    return int(open(path).read().split()[0])

def plot_cm(y_true, y_pred, title, labels=None):
    if labels is None:
        labels = sorted(list(set(y_true) | set(y_pred)))

    cm = confusion_matrix(y_true, y_pred, labels=labels)

    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=labels,
                yticklabels=labels)
    plt.title(f"{title} Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

yolo_true, yolo_pred = [], []

for img_name in os.listdir(yolo_test_img):
    img_path = os.path.join(yolo_test_img, img_name)
    label_path = os.path.join(yolo_test_lbl, img_name.replace('.jpg','.txt'))

    # ground truth
    true_cls = get_label(label_path)
    yolo_true.append(true_cls)

    # prediksi
    result = yolo_model(img_path, verbose=False)

    if len(result[0].boxes) > 0:
        conf = result[0].boxes.conf.cpu().numpy()
        cls  = result[0].boxes.cls.cpu().numpy().astype(int)

        pred_cls = cls[np.argmax(conf)]
    else:
        pred_cls = -1

    yolo_pred.append(pred_cls)

# filter valid
f_true, f_pred = [], []
for t,p in zip(yolo_true,yolo_pred):
    if t != -1 and p != -1:
        f_true.append(t)
        f_pred.append(p)

plot_cm(f_true, f_pred, "YOLOv8")

def yolo_to_classification(model, images_path, labels_path):
    image_files = sorted(os.listdir(images_path))

    y_true = []
    y_pred = []

    for img_file in image_files:
        img_path = os.path.join(images_path, img_file)

        # ====== GROUND TRUTH ======
        label_file = img_file.replace('.jpg', '.txt')
        label_path = os.path.join(labels_path, label_file)

        if not os.path.exists(label_path):
            continue

        with open(label_path, 'r') as f:
            line = f.readline().strip()
            true_class = int(line.split()[0])

        # ====== PREDIKSI YOLO ======
        results = model(img_path, verbose=False)[0]

        if len(results.boxes) > 0:
            confs = results.boxes.conf.cpu().numpy()
            classes = results.boxes.cls.cpu().numpy()

            best_idx = np.argmax(confs)
            pred_class = int(classes[best_idx])
        else:
            pred_class = -1  # gagal deteksi

        y_true.append(true_class)
        y_pred.append(pred_class)

    return np.array(y_true), np.array(y_pred)

y_true_yolo, y_pred_yolo = yolo_to_classification(
    yolo_model,
    yolo_test_img,
    yolo_test_lbl
)

mask = y_pred_yolo != -1

y_true_yolo = y_true_yolo[mask]
y_pred_yolo = y_pred_yolo[mask]

plot_cm(y_true_yolo, y_pred_yolo, "YOLOv8")

from sklearn.metrics import classification_report

labels = ["anthracnose", "cssvd", "healthy"]

print("\n===== YOLOv8 Classification Report =====")
print(classification_report(y_true_yolo, y_pred_yolo, target_names=labels))

from sklearn.metrics import accuracy_score

yolo_acc = accuracy_score(y_true_yolo, y_pred_yolo)

print("YOLO Accuracy:", yolo_acc)

import pandas as pd

yolo_results = pd.read_csv(
    "/content/drive/MyDrive/Project Individu Deep Learning/Dataset Daun Kokoa/Dataset Daun Kokoa (Yolov8)/results/exp_yolo2/results.csv"
)

yolo_results.head()

import collections

print("Distribusi Prediksi YOLO:")
print(collections.Counter(y_pred_yolo))

import pandas as pd

results = pd.DataFrame({
    "Model": ["CNN", "ResNet50", "YOLOv8"],
    "Accuracy": [cnn_acc, resnet_acc, yolo_acc]
})

print(results)

import matplotlib.pyplot as plt

def plot(history, title):
    plt.figure(figsize=(12,5))

    plt.subplot(1,2,1)
    plt.plot(history.history['accuracy'])
    plt.plot(history.history['val_accuracy'])
    plt.title(title + " Accuracy")
    plt.legend(['train','val'])

    plt.subplot(1,2,2)
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title(title + " Loss")
    plt.legend(['train','val'])

    plt.show()

plot(cnn_history, "CNN")
plot(resnet_history, "ResNet50")

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

# 🔹 Accuracy analog (pakai mAP50)
plt.subplot(1,2,1)
plt.plot(yolo_results['metrics/mAP50(B)'])
plt.title("YOLOv8 mAP50 (Accuracy Proxy)")
plt.xlabel("Epoch")

# 🔹 Loss
plt.subplot(1,2,2)
plt.plot(yolo_results['train/box_loss'])
plt.plot(yolo_results['val/box_loss'])
plt.title("YOLOv8 Loss")
plt.legend(['train','val'])

plt.show()

plt.figure()

plt.plot(cnn_history.history['val_accuracy'], label='CNN')
plt.plot(resnet_history.history['val_accuracy'], label='ResNet50')
plt.plot(yolo_results['metrics/mAP50(B)'], label='YOLOv8')

plt.title("Perbandingan Performa Model")
plt.legend()
plt.show()

plt.figure()

plt.plot(cnn_history.history['val_loss'], label='CNN')
plt.plot(resnet_history.history['val_loss'], label='ResNet50')
plt.plot(yolo_results['val/box_loss'], label='YOLOv8')

plt.title("Perbandingan Loss Model")
plt.legend()
plt.show()

cnn_acc = cnn_model.evaluate(test_gen)[1]
resnet_acc = resnet_model.evaluate(test_gen)[1]
yolo_acc = accuracy_score(f_true, f_pred)

import pandas as pd

results = pd.DataFrame({
    "Model":["CNN","ResNet50","YOLOv8"],
    "Accuracy":[cnn_acc,resnet_acc,yolo_acc]
})

print(results.sort_values(by="Accuracy",ascending=False))

plt.figure()

plt.bar(results["Model"], results["Accuracy"])

plt.title("Perbandingan Akurasi Model")
plt.xlabel("Model")
plt.ylabel("Accuracy")

# tampilkan nilai di atas bar
for i, v in enumerate(results["Accuracy"]):
    plt.text(i, v + 0.01, f"{v:.2f}", ha='center')

plt.ylim(0,1)
plt.show()

"""**Prediksi Contoh Citra Dengan 3 Model**"""

import random
import cv2
import numpy as np
import matplotlib.pyplot as plt

# ambil gambar random
img_path = random.choice(test_gen.filepaths)

# load gambar
img = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)

# ========================
# 🔹 PREPROCESS CNN & RESNET
# ========================
img_resized = cv2.resize(img, (224,224)) / 255.0
img_input = np.expand_dims(img_resized, axis=0)

# CNN
pred_cnn = cnn_model.predict(img_input)
cnn_class = class_names[np.argmax(pred_cnn)]
cnn_conf  = np.max(pred_cnn)

# ResNet
pred_resnet = resnet_model.predict(img_input)
resnet_class = class_names[np.argmax(pred_resnet)]
resnet_conf  = np.max(pred_resnet)

# ========================
# 🔴 YOLO
# ========================
yolo_result = yolo_model(img_path, verbose=False)

img_yolo = img.copy()

if len(yolo_result[0].boxes) > 0:
    boxes = yolo_result[0].boxes.xyxy.cpu().numpy()
    confs = yolo_result[0].boxes.conf.cpu().numpy()
    classes_yolo = yolo_result[0].boxes.cls.cpu().numpy().astype(int)

    # ambil prediksi terbaik (confidence tertinggi)
    best_idx = np.argmax(confs)
    yolo_class = class_names[classes_yolo[best_idx]]
    yolo_conf  = confs[best_idx]

    # gambar semua bounding box
    for box, conf, cls in zip(boxes, confs, classes_yolo):
        x1, y1, x2, y2 = map(int, box)
        label = f"{class_names[cls]} ({conf:.2f})"

        cv2.rectangle(img_yolo, (x1,y1), (x2,y2), (0,255,0), 2)
        cv2.putText(img_yolo, label,
                    (x1, y1-10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.6,
                    (0,255,0),
                    2)
else:
    yolo_class = "Tidak terdeteksi"
    yolo_conf  = 0

# ========================
# 🖨️ OUTPUT TEXT
# ========================
print("=== HASIL KLASIFIKASI ===")
print(f"CNN     : {cnn_class} ({cnn_conf:.2f})")
print(f"ResNet  : {resnet_class} ({resnet_conf:.2f})")
print(f"YOLOv8  : {yolo_class} ({yolo_conf:.2f})")

# ========================
# 📊 VISUALISASI
# ========================
plt.figure(figsize=(12,4))

# CNN
plt.subplot(1,3,1)
plt.imshow(img)
plt.title(f"CNN\n{cnn_class} ({cnn_conf:.2f})")
plt.axis('off')

# ResNet
plt.subplot(1,3,2)
plt.imshow(img)
plt.title(f"ResNet\n{resnet_class} ({resnet_conf:.2f})")
plt.axis('off')

# YOLO
plt.subplot(1,3,3)
plt.imshow(img_yolo)
plt.title(f"YOLOv8\n{yolo_class} ({yolo_conf:.2f})")
plt.axis('off')

plt.tight_layout()
plt.show()